name: sharding-repl-cache

services:
  # ------------------------------
  # Config Server Replica Set (3)
  # ------------------------------
  configSrv1:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--bind_ip_all"]
    volumes:
      - configSrv1_data:/data/db

  configSrv2:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--bind_ip_all"]
    volumes:
      - configSrv2_data:/data/db

  configSrv3:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--bind_ip_all"]
    volumes:
      - configSrv3_data:/data/db

  # ------------------------------
  # Shard 1 Replica Set (3)
  # ------------------------------
  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard1RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard1_3_data:/data/db

  # ------------------------------
  # Shard 2 Replica Set (3)
  # ------------------------------
  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard2RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard2RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard2RS", "--port", "27018", "--bind_ip_all"]
    volumes:
      - shard2_3_data:/data/db

  # ------------------------------
  # mongos router
  # ------------------------------
  mongos:
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on:
      - configSrv1
      - configSrv2
      - configSrv3
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    command:
      [
        "mongos",
        "--configdb",
        "configReplSet/configSrv1:27019,configSrv2:27019,configSrv3:27019",
        "--port",
        "27017",
        "--bind_ip_all"
      ]
    ports:
      - "27017:27017"

  # ------------------------------
  # Application
  # ------------------------------
  pymongo_api:
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  configSrv1_data:
  configSrv2_data:
  configSrv3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
  redis_data:
